name: quiz_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  side_navigation: ^1.0.4
  data_table_2: ^2.5.18
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  flutter_quill: ^10.8.5
  percent_indicator: ^4.2.4
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  device_preview: ^1.2.0
  uuid: ^4.5.1
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/preloader.png
    - assets/images/USA.png
    - assets/images/UK.png
    - assets/images/PORTUGAL.png
    - assets/images/FRANCE.png
    - assets/images/BOLIVIA.png
    - assets/images/BELGIUM.png
    - assets/images/twitter.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/settings-gears 1.png
    - assets/images/share.png
    - assets/images/PP.png
    - assets/images/TAC.png
    # ============= icons =================
    - assets/icons/Icon1SideA.png
    - assets/icons/Icon1SideB.png
    - assets/icons/Icon2SideA.png
    - assets/icons/Icon2SideB.png
    - assets/icons/Icon3SideA.png
    - assets/icons/Icon3SideB.png
    - assets/icons/Icon4SideA.png
    - assets/icons/Icon4SideB.png
    - assets/icons/Icon5SideA.png
    - assets/icons/Icon5SideB.png
    - assets/icons/Icon6SideA.png
    - assets/icons/Icon6SideB.png
    - assets/icons/Icon7SideA.png
    - assets/icons/Icon7SideB.png
    - assets/icons/Icon8SideA.png
    - assets/icons/Icon8SideB.png
    - assets/icons/Icon9SideA.png
    - assets/icons/Icon9SideB.png
    - assets/icons/Icon10SideA.png
    - assets/icons/Icon10SideB.png
    - assets/icons/Icon11SideA.png
    - assets/icons/Icon11SideB.png
    - assets/icons/Icon12SideA.png
    - assets/icons/Icon12SideB.png
    - assets/icons/Icon13SideA.png
    - assets/icons/Icon13SideB.png
    - assets/icons/Icon14SideA.png
    - assets/icons/Icon14SideB.png
    - assets/icons/Icon15SideA.png
    - assets/icons/Icon15SideB.png
    - assets/icons/Icon16SideA.png
    - assets/icons/Icon16SideB.png
    - assets/icons/Icon17SideA.png
    - assets/icons/Icon17SideB.png
    - assets/icons/Icon18SideA.png
    - assets/icons/Icon18SideB.png
    - assets/icons/Icon19SideA.png
    - assets/icons/Icon19SideB.png
    - assets/icons/Icon20SideA.png
  #   - images/a_dot_ham.jpeg

# assets:
#   - assets/images/preloader.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/static/Urbanist-Regular.ttf
    - family: palatino
      fonts:
        - asset: assets/fonts/Palaino/palatinolinotype_bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
