// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlZ0eWUWvl2uPyfqQvUsDPKLAYYV-nH8',
    appId: '1:816012022940:web:041cac8645066b28c70959',
    messagingSenderId: '816012022940',
    projectId: 'onetwoq-27deb',
    authDomain: 'onetwoq-27deb.firebaseapp.com',
    storageBucket: 'onetwoq-27deb.appspot.com',
    measurementId: 'G-D5VRRQMBJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3U7Jv4ZvDp9ZXqh7MHFd8X8E47Hqy0WM',
    appId: '1:816012022940:android:9b4377707aebf91ac70959',
    messagingSenderId: '816012022940',
    projectId: 'onetwoq-27deb',
    storageBucket: 'onetwoq-27deb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqW0Y3pCoboM6KPF7cshGCBhNj9pO2u9A',
    appId: '1:816012022940:ios:18ab833a38ae9074c70959',
    messagingSenderId: '816012022940',
    projectId: 'onetwoq-27deb',
    storageBucket: 'onetwoq-27deb.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqW0Y3pCoboM6KPF7cshGCBhNj9pO2u9A',
    appId: '1:816012022940:ios:eed7ecabe56ef54fc70959',
    messagingSenderId: '816012022940',
    projectId: 'onetwoq-27deb',
    storageBucket: 'onetwoq-27deb.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
